asm(
    ".section        .reset,\"ax\"	\n"

    ".globl arm966_reset_entry				\n"
    "arm966_reset_entry:					\n"
//    ".set push							\n"
//    ".set noat							\n"

	"   b bootstart                     \n"
	"bootstart:                         \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
	"   b bootstart                     \n"
   );


