asm(
".section \".firmware\",\"ax\" \n"
". = 0x0100\n"
"system_reset_exception:\n"
"_start:\n"
".global _start\n"
"	b start_firmware\n"
". = 0x0200\n"
"machine_check_exception:\n"
"	b machine_check_exception\n"
". = 0x0300\n"
"dsi_exception:\n"
"	b dsi_exception\n"
". = 0x0400\n"
"isi_exception:\n"
"	b isi_exception\n"
". = 0x0500\n"
"external_interrupt:\n"
"	b external_interrupt\n"
". = 0x0600\n"
"alignment_exception:\n"
"	b alignment_exception\n"
". = 0x0700\n"
"program_exception:\n"
"	b program_exception\n"
". = 0x0800\n"
"floating_point_unavailable_exception:\n"
"	b floating_point_unavailable_exception\n"
". = 0x0900\n"
"decrementer_exception:\n"
"	b decrementer_exception\n"
". = 0x0c00\n"
"trace_exception:\n"
"	b trace_exception\n"
". = 0x0e00\n"
"floating_point_assist_exception:\n"
"	b floating_point_assist_exception\n"
". = 0x0f00\n"
"performance_monitor_exception:\n"
"	b performance_monitor_exception\n"
". = 0x0f20\n"
"altivec_unavailable_exception:\n"
"	b altivec_unavailable_exception\n"
". = 0x1000\n"
"itlb_miss_exception:\n"
"	b itlb_miss_exception\n"
". = 0x1100\n"
"dtlb_miss_on_load_exception:\n"
"	b dtlb_miss_on_load_exception\n"
". = 0x1200\n"
"dtlb_miss_on_store_exception:\n"
"	b dtlb_miss_on_store_exception\n"
". = 0x1300\n"
"instruction_address_breakpoint_exception:\n"
"	b instruction_address_breakpoint_exception\n"
". = 0x1400\n"
"system_management_interrupt:\n"
"	b system_management_interrupt\n"
". = 0x1600\n"
"altivec_assist_exception:\n"
"	b altivec_assist_exception\n"
);
