
cluster : multi_cluster_top.desc multi_cluster_top.cpp
	soclib-cc -m debug -P -p multi_cluster_top.desc -o simul.x

clean:
	soclib-cc -x -p multi_cluster_top.desc 
	rm -f *.o *.x core tmp temp *.deps stats trace simul*

